### PR TITLE
Getting Ready for Rails 7

### PR DESCRIPTION
**Pull request by reckerswartz**
Support Rails 7.0.0.alpha2

### CODE REVIEW

**Comment by flyerhzm** [comment]
@reckerswartz it breaks the integration tests and I have to revert the PR

**Comment by reckerswartz** [comment]
will try to fix the test.

**Comment by reckerswartz** [comment]
@flyerhzm how to run tests?

**Comment by reckerswartz** [comment]
got it patching it.
Thanks

**Pull request merged**
