### PR TITLE
Support active record 7.2.0

### PR DESCRIPTION
**Pull request by hatsu38**
Rails 7.2 is expected to be released soon, so I made this PR to support ActiveRecord 7.2.0.
https://rubygems.org/gems/rails/versions/7.2.0.beta1

Changes:

- Updated dependencies to work with ActiveRecord 7.2.0
- Made necessary code adjustments (The arguments of the `find_by_sql` method have changed.)

### CODE REVIEW

**Comment by fatkodima** [comment]
Thank you for working on this! ❤️ Do you plan to finish this PR soon?

**Comment by hatsu38** [comment]
Finished the draft for the pull request and made it public. However, I still don't understand why the CI is failing...

**Comment by vbiletskii** [comment]
> Finished the draft for the pull request and made it public. However, I still don't understand why the CI is failing...

@hatsu38 great work on this PR! I think the CI issue might be fixed by pinning sqlite3 to version `1.4` in the `Gemfile.rails-7.0`. Just a suggestion to help get this PR live

**Comment by hatsu38** [comment]
@vbiletskii @fatkodima Thanks! I fixed it.⚒️

**Comment by fatkodima** [comment]
I think it is also a good idea to squash commits into one. 
Hopefully this will be merged and released soon.

**Comment by flyerhzm** [comment]
@hatsu38 thank you so much for supporting active record 7.2.0

**Pull request merged**
