### PR TITLE
Rails 7 patch

### PR DESCRIPTION
**Pull request by reckerswartz**

### CODE REVIEW

**Comment by reckerswartz** [comment]
@flyerhzm I need help here in getting started.

Mostly Error I can think of the issue because of.

The forthcoming Rails 7 represents a milestone for autoloading.

There are two important changes coming:

  *  Zeitwerk has been the default autoloader for more than two years. Rails 6.0 and Rails 6.1 supported both zeitwerk and classic modes to help projects transition. This period ends with Rails 7: classic mode won’t be available anymore.

 *  Initializers can autoload reloadable constants if wrapped in to_prepare blocks, but they no longer can otherwise.


Also might need to add Support for  :- 

#### Asynchronous Query Loading

When you have a controller action that needs to load two unrelated queries, you can now do it concurrently through Relation#load_async. If you have three complex queries that each take 100ms, you’d have to spend 300ms executing them one by one before. Now you can run them in parallel, spending only a total of 100ms on the set.

**Comment by guillaumebriday-pa** [comment]
Great! With the release of the RC version today of Rails 7, that would be awesome to have this PR merged 👍 

Thanks for the Gem

**Comment by dhekimian** [comment]
https://weblog.rubyonrails.org/2021/12/11/this-week-in-rails-rails-7-0-rc1-faster-template-rendering-better-tests-and-much-more-401a9df5/

> With tons of new features and improvements like new ways to deal with JavaScript or at-work encryption, this new version of Rails should be released before Christmas!

It might be a good idea to get this merged before more people come looking for it.

**Comment by jon-sully** [comment]
> more people come looking for it.

We have come looking 🤣 but thanks for all the work on this, everyone

**Comment by flyerhzm** [comment]
there are too many test failures, I don't think I can merge it, but I'm working on the rails 7 compatibility.

**Comment by flyerhzm** [comment]
close this PR, master branch has  already supported rails 7, but it doesn't work well with `inverse_of` option, there's still one test failure, I'll keep working on it.

**Pull request closed without merging**
