### PR TITLE
Add support for ActiveRecord 5.2

### PR DESCRIPTION
**Pull request by madrobby**
In ActiveRecord 5.2 (aka current edge Rails) there was a small change to the `instantiate` method on join dependencies (see rails/rails@1a723c6).

I've no idea how to test this properly, so tests should be added to this PR.

### CODE REVIEW

**Comment by flyerhzm** [comment]
@madrobby sorry for the late reply, is there any difference between `lib/bullet/active_record5.rb` and `lib/bullet/active_record52.rb`, if not, it's not necessary to add active_record52

**Comment by prathamesh-sonpatki** [comment]
@madrobby Still interested in pursuing this?

**Comment by madrobby** [comment]
You still need the patch to make Bullet work with Rails 5.2. There’s a Rails 5.2 beta out now, fwiw.

**Comment by flyerhzm** [comment]
@madrobby I figured out the difference between `active_record5` and `active_record52`, thanks for your patch.

**Comment by flyerhzm** [comment]
just released 5.7.0 to support rails 5.2

**Pull request merged**
