### PR TITLE
Quit CIing against Rubies < 2.7 and Rails < 4.2

### PR DESCRIPTION
**Pull request by amatsuda**
This follows up bc8c3e6fe8f320e8de916de19b54982aefb34f18.

TBH I'm not sure if Ruby 2.7 can run all the tests here on Rails 4, but let's try anyway.

### CODE REVIEW

**Comment by amatsuda** [comment]
Currently happening error on Rails 4.0 and 4.1 has been fixed with [this patch](https://github.com/rails/arel/pull/439) in Arel 6, and this patch was not back ported to neither Arel 4 nor Arel 5.

So I think there are two options for us:
1. Bring Ruby 2.4 support back, and run Rails 4 CI on Ruby 2.4
2. Drop Rails 4.0 and 4.1 support

WDYT?

**Comment by flyerhzm** [comment]
@amatsuda I was trying to upgrading ruby to 2.7.0 but not done yet, thanks for helping.
I prefer dropping rails 4.0 and 4.1 support.

**Comment by amatsuda** [comment]
@flyerhzm OK, added another commit that drops Rails < 4.2 from the CI.

**Comment by flyerhzm** [comment]
@amatsuda thank you.

**Pull request merged**
