### PR TITLE
Add Support ActiveRecord 7.1.0

### PR DESCRIPTION
**Pull request by hatsu38**
I always use BULLET.

When rails7.1.0.beta1 was released and I was trying it out, I discovered that it is not supported by this Gem.

I would like to be able to use bullets in 7.1 as well.

### CODE REVIEW

**Comment by navidemad** [comment]
Can you try to change it to [7.1.0.rc2](https://rubygems.org/gems/rails/versions/7.1.0.rc2) ?

**Comment by PikachuEXE** [comment]
`gem install rails -v '~> 7.1.0.beta1'` will make bundler install `7.1.0.rc2` (and `7.1.x` if they are released) assuming there is no version lock

**Comment by hatsu38** [comment]
According to this article, Rails 7.1.0 is scheduled to be released on October 5th. I am planning to upgrade the version once it's released.

https://rubyonrails.org/2023/10/1/Rails-Rails-7-1-enters-the-release-candidate-phase

**Comment by euglena1215** [comment]
I think it is valuable to merge support up to 7.1.0.rc2 into the main branch early.

If we want to run a Rails application using `bullet` gem in a Rails 7.1 environment now, we need to remove the `bullet` gem. (including changes to the initializer).
It is more useful to change the bullet gem designation from the latest version to the main branch.

**Comment by joshRpowell** [comment]
rails 7.1 was released https://github.com/rails/rails/releases/tag/v7.1.0

**Comment by flyerhzm** [comment]
@hatsu38 As activerecord 7.1 was released, I'm glad to support it in bullet, please change the dependency to rails 7.1, or I'll do it by myself, thanks.

**Comment by cristi** [comment]
looking forward to seeing this released. It prevents people from upgrading rails

```ruby
Bundler::GemRequireError: There was an error while trying to load the gem 'bullet'.
```

thanks for the amazing work!

**Pull request merged**
