### PR TITLE
Do not report association queries immediately after object creation to require a preload

### LINKED ISSUE #243: False N+1 warning when querying immediately after creation
Assuming two models: User has many emails.
The email= mutator creates an email record.

```ruby
Bullet.profile do
  u = User.create(name: 'Test', email: 'lol3@example.com', password: 'hehehehe')
  u.emails.any?(&:changed?)
end
```

In this case, the emails association is already loaded and all calls to the association will not hit the database.

### PR DESCRIPTION
**Pull request by lowjoel**
Fixes #243.

### CODE REVIEW

**Comment by lowjoel** [comment]
This currently is only applied to AR4.2 because I'm not sure if this is the right direction.

**Comment by flyerhzm** [comment]
@lowjoel it breaks the tests

**Comment by lowjoel** [comment]
@flyerhzm like I've said, I've only applied the fix on AR4.2. If you think it's the correct fix, then I'll apply the fix for AR4.1 and 4.0.

It appears AR3 isn't affected.

**Comment by flyerhzm** [comment]
@lowjoel I'd like to merge this pull request if all tests passed.

**Comment by lowjoel** [comment]
Thanks! Is mongo5 supposed to fail?

**Comment by flyerhzm** [comment]
@lowjoel if you don't change tests for mongoid, it won't fail

**Comment by lowjoel** [comment]
Seems to be passing for AR4 and AR4.1

mongoid5 is failing because the gem doesn't exist...

I'll probably submit another PR to switching to using the container infrastructure to speed up the build time.

**Comment by lowjoel** [comment]
@flyerhzm the AR tests all pass now; mongo is still failing because of a missing gem for mongoid 5.0

**Comment by lowjoel** [comment]
Merging #246 will make this pass.

**Comment by flyerhzm** [comment]
@lowjoel thanks a lot

**Pull request merged**
