### PR TITLE
Wip for Rails 6

### PR DESCRIPTION
**Pull request by duduribeiro**
Hey folks 👋, I don't know if this PR is valid. I'm working on a pet project that I'm using Rails 6 alpha and I added this Wip for bullet to work with rails 6.

What do you folks think about it?

### CODE REVIEW

**Comment by pacso** [comment]
I've started a Rails 6 branch in a private project of mine, and am using this branch to get Bullet working against Rails 6. So far no issues ...

**Comment by msdundar** [comment]
Nop, it's not working and returing:

`Gem Load Error is: Bullet does not support active_record 6.0.0.beta1 yet` error.

**Comment by pacso** [comment]
Are you sure you're using this branch @msdundar ? Can you paste the appropriate line from your `Gemfile`?

**Comment by mmzoo** [comment]
Thank you @flyerhzm

**Pull request merged**
